#!/bin/bash

################################################################################
# DataK9 Interactive Demo
#
# Comprehensive demonstration of DataK9 data validation framework features.
# This script provides an interactive menu to showcase validation, profiling,
# testing, and reporting capabilities.
#
# All demo artifacts are stored in demo-tmp/ directory which can be optionally
# cleaned up on exit.
#
# Author: Daniel Edge
################################################################################

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Demo configuration
DEMO_DIR="demo-tmp"
CONFIGS_DIR="$DEMO_DIR/configs"
REPORTS_DIR="$DEMO_DIR/reports"
PROFILES_DIR="$DEMO_DIR/profiles"
BACKUP_DIR="$DEMO_DIR/config-backups"
SAMPLE_DATA_DIR="examples/sample_data"

# Config file templates
CUSTOMERS_CONFIG="$CONFIGS_DIR/customers_validation.yaml"
TRANSACTIONS_CONFIG="$CONFIGS_DIR/transactions_validation.yaml"
ACCOUNTS_CONFIG="$CONFIGS_DIR/accounts_validation.yaml"
CROSS_FILE_CONFIG="$CONFIGS_DIR/cross_file_validation.yaml"

################################################################################
# Helper Functions
################################################################################

print_logo() {
    if [ -f "resources/images/ascii-art.txt" ]; then
        cat resources/images/ascii-art.txt
        echo ""
        echo -e "${CYAN}                    INTERACTIVE DEMO${NC}"
        echo ""
    else
        echo -e "${CYAN}"
        echo "╔══════════════════════════════════════════════════════════════════╗"
        echo "║                                                                  ║"
        echo "║                  DataK9 - INTERACTIVE DEMO                      ║"
        echo "║                                                                  ║"
        echo "╚══════════════════════════════════════════════════════════════════╝"
        echo -e "${NC}"
    fi
}

print_section() {
    echo -e "\n${WHITE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${WHITE}  $1${NC}"
    echo -e "${WHITE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

################################################################################
# Setup and Initialization
################################################################################

setup_demo_environment() {
    print_section "Setting Up Demo Environment"

    # Create demo directories
    mkdir -p "$DEMO_DIR" "$CONFIGS_DIR" "$REPORTS_DIR" "$PROFILES_DIR" "$BACKUP_DIR"

    if [ $? -eq 0 ]; then
        print_success "Created demo directory structure"
        print_info "Demo files will be stored in: $DEMO_DIR/"
    else
        print_error "Failed to create demo directories"
        return 1
    fi

    # Check if sample data exists
    if [ ! -d "$SAMPLE_DATA_DIR" ]; then
        print_error "Sample data directory not found: $SAMPLE_DATA_DIR"
        print_info "Run: python3 examples/generate_sample_data.py"
        return 1
    fi

    # Count sample data files
    local data_files=$(ls -1 $SAMPLE_DATA_DIR/*.csv 2>/dev/null | wc -l)
    print_success "Found $data_files sample data files"

    # Generate default config files if they don't exist
    generate_default_configs

    echo ""
    return 0
}

################################################################################
# Configuration File Generation
################################################################################

generate_default_configs() {
    print_info "Generating default validation configurations..."

    # Generate customers validation config
    cat > "$CUSTOMERS_CONFIG" << 'EOF'
# DataK9 Validation Configuration - Customer Data
# Generated by demo.sh

validation_job:
  name: "Customer Data Validation Demo"
  version: "1.0"

  files:
    - name: "customers"
      path: "examples/sample_data/customers.csv"
      format: "csv"

      validations:
        # File-level checks
        - type: "EmptyFileCheck"
          severity: "ERROR"

        - type: "RowCountRangeCheck"
          severity: "WARNING"
          params:
            min_rows: 100
            max_rows: 10000

        # Schema checks
        - type: "ColumnPresenceCheck"
          severity: "ERROR"
          params:
            required_columns:
              - customer_id
              - first_name
              - last_name
              - email
              - phone
              - account_balance
              - registration_date
              - status

        # Field-level validations
        - type: "MandatoryFieldCheck"
          severity: "ERROR"
          params:
            columns:
              - customer_id
              - email
              - status

        - type: "RegexCheck"
          severity: "ERROR"
          params:
            column: "email"
            pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
            description: "Valid email format"

        - type: "RegexCheck"
          severity: "WARNING"
          params:
            column: "phone"
            pattern: "^\\+1[0-9]{10}$"
            description: "Valid US phone format (+1XXXXXXXXXX)"

        - type: "ValidValuesCheck"
          severity: "ERROR"
          params:
            column: "status"
            valid_values:
              - "ACTIVE"
              - "INACTIVE"
              - "SUSPENDED"
              - "PENDING"

        - type: "RangeCheck"
          severity: "WARNING"
          params:
            column: "account_balance"
            min_value: 0
            max_value: 10000000
            description: "Balance between $0 and $10M"

        - type: "DateFormatCheck"
          severity: "ERROR"
          params:
            column: "registration_date"
            date_format: "%Y-%m-%d"

        # Record-level validations
        - type: "DuplicateRowCheck"
          severity: "ERROR"
          params:
            key_columns:
              - customer_id

        # Advanced validations
        - type: "CompletenessCheck"
          severity: "WARNING"
          params:
            column: "phone"
            min_completeness: 95.0

  # Output configuration
  html_report_path: "demo-tmp/reports/customers_validation_report.html"
  json_summary_path: "demo-tmp/reports/customers_validation_summary.json"
  fail_on_error: false
  fail_on_warning: false
EOF

    # Generate transactions validation config
    cat > "$TRANSACTIONS_CONFIG" << 'EOF'
# DataK9 Validation Configuration - Transaction Data
# Generated by demo.sh

validation_job:
  name: "Transaction Data Validation Demo"
  version: "1.0"

  files:
    - name: "transactions"
      path: "examples/sample_data/transactions.csv"
      format: "csv"

      validations:
        # File-level checks
        - type: "EmptyFileCheck"
          severity: "ERROR"

        - type: "FileSizeCheck"
          severity: "WARNING"
          params:
            min_size_bytes: 100
            max_size_bytes: 10485760  # 10 MB

        # Schema checks
        - type: "ColumnPresenceCheck"
          severity: "ERROR"
          params:
            required_columns:
              - transaction_id
              - customer_id
              - amount
              - status

        # Field-level validations
        - type: "MandatoryFieldCheck"
          severity: "ERROR"
          params:
            columns:
              - transaction_id
              - amount
              - status

        - type: "RegexCheck"
          severity: "ERROR"
          params:
            column: "transaction_id"
            pattern: "^TXN[0-9]{10}$"
            description: "Transaction ID format: TXN followed by 10 digits"

        - type: "ValidValuesCheck"
          severity: "ERROR"
          params:
            column: "status"
            valid_values:
              - "COMPLETED"
              - "PENDING"
              - "FAILED"
              - "CANCELLED"

        - type: "RangeCheck"
          severity: "ERROR"
          params:
            column: "amount"
            min_value: 0.01
            max_value: 100000.00
            description: "Transaction amount between $0.01 and $100,000"

        # Record-level validations
        - type: "DuplicateRowCheck"
          severity: "WARNING"
          params:
            key_columns:
              - transaction_id

        # Advanced validations
        - type: "CompletenessCheck"
          severity: "WARNING"
          params:
            column: "customer_id"
            min_completeness: 98.0

  # Output configuration
  html_report_path: "demo-tmp/reports/transactions_validation_report.html"
  json_summary_path: "demo-tmp/reports/transactions_validation_summary.json"
  fail_on_error: false
  fail_on_warning: false
EOF

    # Generate accounts validation config
    cat > "$ACCOUNTS_CONFIG" << 'EOF'
# DataK9 Validation Configuration - Account Data
# Generated by demo.sh

validation_job:
  name: "Account Data Validation Demo"
  version: "1.0"

  files:
    - name: "accounts"
      path: "examples/sample_data/accounts.csv"
      format: "csv"

      validations:
        # File-level checks
        - type: "EmptyFileCheck"
          severity: "ERROR"

        # Schema checks
        - type: "ColumnPresenceCheck"
          severity: "ERROR"
          params:
            required_columns:
              - account_id
              - account_number
              - customer_id
              - account_type
              - opening_balance
              - opening_date

        # Field-level validations
        - type: "MandatoryFieldCheck"
          severity: "ERROR"
          params:
            columns:
              - account_id
              - account_number
              - account_type

        - type: "ValidValuesCheck"
          severity: "ERROR"
          params:
            column: "account_type"
            valid_values:
              - "SAVINGS"
              - "CHECKING"
              - "CREDIT"
              - "INVESTMENT"

        - type: "RangeCheck"
          severity: "WARNING"
          params:
            column: "opening_balance"
            min_value: 0
            max_value: 1000000
            description: "Opening balance between $0 and $1M"

        - type: "DateFormatCheck"
          severity: "ERROR"
          params:
            column: "opening_date"
            date_format: "%Y-%m-%d"

        # Record-level validations
        - type: "DuplicateRowCheck"
          severity: "ERROR"
          params:
            key_columns:
              - account_id

        - type: "UniqueKeyCheck"
          severity: "ERROR"
          params:
            column: "account_number"

  # Output configuration
  html_report_path: "demo-tmp/reports/accounts_validation_report.html"
  json_summary_path: "demo-tmp/reports/accounts_validation_summary.json"
  fail_on_error: false
  fail_on_warning: false
EOF

    # Create backups of original configs
    cp "$CUSTOMERS_CONFIG" "$BACKUP_DIR/customers_validation.yaml.original" 2>/dev/null
    cp "$TRANSACTIONS_CONFIG" "$BACKUP_DIR/transactions_validation.yaml.original" 2>/dev/null
    cp "$ACCOUNTS_CONFIG" "$BACKUP_DIR/accounts_validation.yaml.original" 2>/dev/null

    print_success "Generated 3 validation configuration files"
    print_info "Configs stored in: $CONFIGS_DIR/"
}

restore_default_configs() {
    print_section "Restoring Default Configurations"

    if [ -d "$BACKUP_DIR" ] && [ "$(ls -A $BACKUP_DIR)" ]; then
        cp "$BACKUP_DIR/customers_validation.yaml.original" "$CUSTOMERS_CONFIG" 2>/dev/null
        cp "$BACKUP_DIR/transactions_validation.yaml.original" "$TRANSACTIONS_CONFIG" 2>/dev/null
        cp "$BACKUP_DIR/accounts_validation.yaml.original" "$ACCOUNTS_CONFIG" 2>/dev/null

        print_success "Restored all configuration files to defaults"
    else
        print_warning "No backups found, regenerating default configs..."
        generate_default_configs
    fi

    echo ""
    read -p "Press Enter to continue..."
}

################################################################################
# Validation Functions
################################################################################

validate_customers() {
    print_section "Validating Customer Data"

    print_info "Dataset: examples/sample_data/customers.csv"
    print_info "Config: $CUSTOMERS_CONFIG"
    echo ""

    # Run validation with full output visible
    python3 -m validation_framework.cli validate "$CUSTOMERS_CONFIG"
    local exit_code=$?

    echo ""
    print_info "Reports generated:"
    print_info "  HTML: $REPORTS_DIR/customers_validation_report.html"
    print_info "  JSON: $REPORTS_DIR/customers_validation_summary.json"

    echo ""
    read -p "Press Enter to continue..."
}

validate_transactions() {
    print_section "Validating Transaction Data"

    print_info "Dataset: examples/sample_data/transactions.csv"
    print_info "Config: $TRANSACTIONS_CONFIG"
    echo ""

    # Run validation with full output visible
    python3 -m validation_framework.cli validate "$TRANSACTIONS_CONFIG"
    local exit_code=$?

    echo ""
    print_info "Reports generated:"
    print_info "  HTML: $REPORTS_DIR/transactions_validation_report.html"
    print_info "  JSON: $REPORTS_DIR/transactions_validation_summary.json"

    echo ""
    read -p "Press Enter to continue..."
}

validate_accounts() {
    print_section "Validating Account Data"

    print_info "Dataset: examples/sample_data/accounts.csv"
    print_info "Config: $ACCOUNTS_CONFIG"
    echo ""

    # Run validation with full output visible
    python3 -m validation_framework.cli validate "$ACCOUNTS_CONFIG"
    local exit_code=$?

    echo ""
    print_info "Reports generated:"
    print_info "  HTML: $REPORTS_DIR/accounts_validation_report.html"
    print_info "  JSON: $REPORTS_DIR/accounts_validation_summary.json"

    echo ""
    read -p "Press Enter to continue..."
}

validate_all_datasets() {
    print_section "Validating All Datasets"

    echo -e "${CYAN}Running validations for all 3 datasets...${NC}\n"

    local temp_error=$(mktemp)

    # Customers
    echo -e "${WHITE}[1/3] Customers${NC}"
    python3 -m validation_framework.cli validate "$CUSTOMERS_CONFIG" > /dev/null 2>"$temp_error"
    if [ $? -eq 0 ]; then
        print_success "Customers validated"
    elif grep -q "ConfigError" "$temp_error"; then
        print_error "Customers config error"
    else
        print_warning "Customers validation found issues"
    fi

    # Transactions
    echo -e "${WHITE}[2/3] Transactions${NC}"
    python3 -m validation_framework.cli validate "$TRANSACTIONS_CONFIG" > /dev/null 2>"$temp_error"
    if [ $? -eq 0 ]; then
        print_success "Transactions validated"
    elif grep -q "ConfigError" "$temp_error"; then
        print_error "Transactions config error"
    else
        print_warning "Transactions validation found issues"
    fi

    # Accounts
    echo -e "${WHITE}[3/3] Accounts${NC}"
    python3 -m validation_framework.cli validate "$ACCOUNTS_CONFIG" > /dev/null 2>"$temp_error"
    if [ $? -eq 0 ]; then
        print_success "Accounts validated"
    elif grep -q "ConfigError" "$temp_error"; then
        print_error "Accounts config error"
    else
        print_warning "Accounts validation found issues"
    fi

    rm -f "$temp_error"

    echo ""
    print_success "All validations completed"
    print_info "Reports available in: $REPORTS_DIR/"

    echo ""
    read -p "Press Enter to continue..."
}

################################################################################
# Profiling Functions
################################################################################

profile_customers() {
    print_section "Profiling Customer Data"

    print_info "Generating comprehensive data profile..."
    echo ""

    python3 -m validation_framework.cli profile \
        examples/sample_data/customers.csv \
        -o "$PROFILES_DIR/customers_profile_report.html" \
        -c "$CONFIGS_DIR/customers_auto_config.yaml"

    echo ""
    print_success "Customer data profiling completed"
    print_info "HTML Profile: $PROFILES_DIR/customers_profile_report.html"
    print_info "Auto Config: $CONFIGS_DIR/customers_auto_config.yaml"

    echo ""
    read -p "Press Enter to continue..."
}

profile_transactions() {
    print_section "Profiling Transaction Data"

    print_info "Generating comprehensive data profile..."
    echo ""

    python3 -m validation_framework.cli profile \
        examples/sample_data/transactions.csv \
        -o "$PROFILES_DIR/transactions_profile_report.html" \
        -c "$CONFIGS_DIR/transactions_auto_config.yaml"

    echo ""
    print_success "Transaction data profiling completed"
    print_info "HTML Profile: $PROFILES_DIR/transactions_profile_report.html"
    print_info "Auto Config: $CONFIGS_DIR/transactions_auto_config.yaml"

    echo ""
    read -p "Press Enter to continue..."
}

profile_accounts() {
    print_section "Profiling Account Data"

    print_info "Generating comprehensive data profile..."
    echo ""

    python3 -m validation_framework.cli profile \
        examples/sample_data/accounts.csv \
        -o "$PROFILES_DIR/accounts_profile_report.html" \
        -c "$CONFIGS_DIR/accounts_auto_config.yaml"

    echo ""
    print_success "Account data profiling completed"
    print_info "HTML Profile: $PROFILES_DIR/accounts_profile_report.html"
    print_info "Auto Config: $CONFIGS_DIR/accounts_auto_config.yaml"

    echo ""
    read -p "Press Enter to continue..."
}

profile_all_datasets() {
    print_section "Profiling All Datasets"

    echo -e "${CYAN}Generating profiles for all 3 datasets...${NC}\n"

    # Customers
    echo -e "${WHITE}[1/3] Profiling Customers${NC}"
    python3 -m validation_framework.cli profile examples/sample_data/customers.csv \
        -o "$PROFILES_DIR/customers_profile_report.html" \
        -c "$CONFIGS_DIR/customers_auto_config.yaml" > /dev/null 2>&1
    print_success "Customers profiled"

    # Transactions
    echo -e "${WHITE}[2/3] Profiling Transactions${NC}"
    python3 -m validation_framework.cli profile examples/sample_data/transactions.csv \
        -o "$PROFILES_DIR/transactions_profile_report.html" \
        -c "$CONFIGS_DIR/transactions_auto_config.yaml" > /dev/null 2>&1
    print_success "Transactions profiled"

    # Accounts
    echo -e "${WHITE}[3/3] Profiling Accounts${NC}"
    python3 -m validation_framework.cli profile examples/sample_data/accounts.csv \
        -o "$PROFILES_DIR/accounts_profile_report.html" \
        -c "$CONFIGS_DIR/accounts_auto_config.yaml" > /dev/null 2>&1
    print_success "Accounts profiled"

    echo ""
    print_success "All data profiling completed"
    print_info "Profiles available in: $PROFILES_DIR/"

    echo ""
    read -p "Press Enter to continue..."
}

################################################################################
# Report Viewing Functions
################################################################################

view_reports() {
    print_section "View Generated Reports"

    echo "Available reports:"
    echo ""

    local report_count=0

    # List validation reports
    if [ -d "$REPORTS_DIR" ] && [ "$(ls -A $REPORTS_DIR/*.html 2>/dev/null)" ]; then
        echo -e "${WHITE}Validation Reports:${NC}"
        ls -1 "$REPORTS_DIR"/*.html 2>/dev/null | while read report; do
            echo "  - $(basename $report)"
            ((report_count++))
        done
        echo ""
    fi

    # List profile reports
    if [ -d "$PROFILES_DIR" ] && [ "$(ls -A $PROFILES_DIR/*.html 2>/dev/null)" ]; then
        echo -e "${WHITE}Profile Reports:${NC}"
        ls -1 "$PROFILES_DIR"/*.html 2>/dev/null | while read report; do
            echo "  - $(basename $report)"
            ((report_count++))
        done
        echo ""
    fi

    # Show file counts
    local html_count=$(find "$DEMO_DIR" -name "*.html" 2>/dev/null | wc -l)
    local json_count=$(find "$DEMO_DIR" -name "*.json" 2>/dev/null | wc -l)
    local yaml_count=$(find "$DEMO_DIR" -name "*.yaml" 2>/dev/null | wc -l)

    print_info "Total: $html_count HTML reports, $json_count JSON summaries, $yaml_count YAML configs"

    echo ""
    echo "To view reports:"
    echo "  - HTML reports: open demo-tmp/reports/*.html in browser"
    echo "  - JSON summaries: cat demo-tmp/reports/*.json"
    echo "  - Profile reports: open demo-tmp/profiles/*.html in browser"

    echo ""
    read -p "Press Enter to continue..."
}

list_demo_files() {
    print_section "Demo Files and Artifacts"

    if [ -d "$DEMO_DIR" ]; then
        echo -e "${WHITE}Directory Structure:${NC}"
        tree -L 2 "$DEMO_DIR" 2>/dev/null || find "$DEMO_DIR" -maxdepth 2 -type f -o -type d

        echo ""
        local total_size=$(du -sh "$DEMO_DIR" | awk '{print $1}')
        print_info "Total demo artifacts size: $total_size"
    else
        print_warning "Demo directory not found"
    fi

    echo ""
    read -p "Press Enter to continue..."
}

################################################################################
# Testing Functions
################################################################################

run_framework_tests() {
    print_section "Running Framework Tests"

    echo "Select test suite:"
    echo ""
    echo "  1) Run All Tests"
    echo "  2) Run Unit Tests Only"
    echo "  3) Run Integration Tests Only"
    echo "  4) Run with Coverage Report"
    echo "  0) Back to Main Menu"
    echo ""
    read -p "Enter choice [0-4]: " test_choice

    case $test_choice in
        1)
            print_info "Running all tests..."
            ./run_tests.sh --all
            ;;
        2)
            print_info "Running unit tests..."
            ./run_tests.sh --unit
            ;;
        3)
            print_info "Running integration tests..."
            ./run_tests.sh --integration
            ;;
        4)
            print_info "Running tests with coverage..."
            ./run_tests.sh --coverage
            ;;
        0)
            return
            ;;
        *)
            print_error "Invalid choice"
            ;;
    esac

    echo ""
    read -p "Press Enter to continue..."
}

################################################################################
# Cleanup Functions
################################################################################

clean_demo_artifacts() {
    print_section "Clean Demo Artifacts"

    if [ ! -d "$DEMO_DIR" ]; then
        print_info "No demo artifacts to clean"
        echo ""
        read -p "Press Enter to continue..."
        return
    fi

    local total_size=$(du -sh "$DEMO_DIR" | awk '{print $1}')
    local file_count=$(find "$DEMO_DIR" -type f | wc -l)

    echo "Demo artifacts:"
    echo "  Directory: $DEMO_DIR/"
    echo "  Files: $file_count"
    echo "  Size: $total_size"
    echo ""

    read -p "Delete all demo artifacts? (y/N): " -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$DEMO_DIR"
        print_success "Demo artifacts deleted"
    else
        print_info "Demo artifacts preserved"
    fi

    echo ""
    read -p "Press Enter to continue..."
}

cleanup_on_exit() {
    echo ""
    print_section "Exit Demo"

    if [ -d "$DEMO_DIR" ]; then
        local total_size=$(du -sh "$DEMO_DIR" | awk '{print $1}')
        local file_count=$(find "$DEMO_DIR" -type f | wc -l)

        echo "Demo artifacts summary:"
        echo "  Files: $file_count"
        echo "  Size: $total_size"
        echo ""

        read -p "Delete demo artifacts on exit? (y/N): " -n 1 -r
        echo

        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$DEMO_DIR"
            print_success "Demo artifacts deleted"
        else
            print_info "Demo artifacts preserved in: $DEMO_DIR/"
        fi
    fi

    echo ""
    print_info "Thank you for exploring DataK9!"
    echo ""
}

################################################################################
# Main Menu
################################################################################

show_main_menu() {
    clear
    print_logo

    echo "Welcome to the DataK9 Interactive Demo!"
    echo ""
    echo "This demo showcases the complete DataK9 data validation framework."
    echo "All generated files are stored in: ${CYAN}$DEMO_DIR/${NC}"
    echo ""

    echo -e "${WHITE}═══ DATA VALIDATION ═══${NC}"
    echo "  1) Validate Customers Dataset"
    echo "  2) Validate Transactions Dataset"
    echo "  3) Validate Accounts Dataset"
    echo "  4) Validate All Datasets"
    echo ""

    echo -e "${WHITE}═══ DATA PROFILING ═══${NC}"
    echo "  5) Profile Customers Dataset"
    echo "  6) Profile Transactions Dataset"
    echo "  7) Profile Accounts Dataset"
    echo "  8) Profile All Datasets"
    echo ""

    echo -e "${WHITE}═══ REPORTS & FILES ═══${NC}"
    echo "  9) View Generated Reports"
    echo "  10) List Demo Files"
    echo ""

    echo -e "${WHITE}═══ TESTING & CONFIG ═══${NC}"
    echo "  11) Run Framework Tests"
    echo "  12) Restore Default Configs"
    echo "  13) Clean Demo Artifacts"
    echo ""

    echo "  0) Exit Demo"
    echo ""
    echo -n "Enter choice [0-13]: "
}

################################################################################
# Main Logic
################################################################################

main() {
    # Initial setup
    if ! setup_demo_environment; then
        echo ""
        print_error "Demo environment setup failed"
        exit 1
    fi

    # Main menu loop
    while true; do
        show_main_menu
        read choice

        case $choice in
            1) validate_customers ;;
            2) validate_transactions ;;
            3) validate_accounts ;;
            4) validate_all_datasets ;;
            5) profile_customers ;;
            6) profile_transactions ;;
            7) profile_accounts ;;
            8) profile_all_datasets ;;
            9) view_reports ;;
            10) list_demo_files ;;
            11) run_framework_tests ;;
            12) restore_default_configs ;;
            13) clean_demo_artifacts ;;
            0)
                cleanup_on_exit
                exit 0
                ;;
            *)
                print_error "Invalid choice. Please try again."
                sleep 2
                ;;
        esac
    done
}

# Run main function
main "$@"
